### ISSUE TITLE
about links broken

### ISSUE THREAD

**Issue by pssguy** [evanodell/hansard#1]
Nice package, thanks

I know you are only passing on what is available but the about links  e.g http://data.parliament.uk/members/172 are broken

I do not think it is part of package but do you know of any resource  for when MP's were first elected

**Comment by evanodell** [comment]
I'm not sure what is going on with that, but I'll pass it on to the UK parliament data team.

**Comment by evanodell** [comment]
The [Members Names Information Service](http://data.parliament.uk/membersdataplatform/memberquery.aspx) has information for when MPs first joined the House, as well as information on ministerial positions, committee memberships, etc. I am in the process of writing an API package for it, it should be up in the next month or so.

**Comment by evanodell** [comment]
The package [mnis](https://cran.r-project.org/package=mnis) is now on CRAN. It can download individual house start dates with the `mnis_BasicDetails` or `mnis_FullBiog` functions, or bulk data with `mnis_Base` function and your own parameters from the [Members' Names Information Service](http://data.parliament.uk/membersdataplatform/memberquery.aspx).
