### ISSUE TITLE
lords_attendance function returning errors

### ISSUE THREAD

**Issue by meenaparam** [evanodell/hansard#4]
Great package Evan!

I was just testing out the `lords_attendance()` function but am not sure what is happening here.

I tried to run the first help file example with the `all` argument , but it returns this error:

```r
x <- lords_attendance('all')
Error: lexical error: invalid char in json text.
                                       http://lda.data.parliament.uk/l
                     (right here) ------^
```

When I try to run the second example with the `date` argument, using `2016-07-12` as the date, `lords_attendance()` does not return a dataframe, although it looks like there should be [data for this date](http://explore.data.parliament.uk/?endpoint=lordsattendances/625506).

``` r
x <- lords_attendance('date') 
Enter date (yyyy-mm-dd): 2016-07-12   
Retrieving page 1 of 1   
The request did not return any data. Please check your search parameters.
```

Any thoughts?

**Comment by evanodell** [comment]
Hi Meena,

There was an issue with the URL encoding. I'm not sure why I didn't notice it before, so thank you very much for pointing it out. I've fixed it the issue in the newest release, which is now on CRAN.

I'm glad to hear you otherwise like the package.

Evan
