### ISSUE TITLE
members search = NULL not returning all data

### ISSUE THREAD

**Issue by poldham** [evanodell/hansard#9]
Dear Evan, 

Many thanks for this great package. I wanted to let you know that the documentation for the members_search() function states that the NULL default should return a full tibble with all members. However it is 404ing for me with `Error in open.connection(con, "rb") : HTTP error 404.` .  From a quick look I can't see any obvious problem with the code for the fun. I took a look at the tests and  under testthat/test_members noticed the memempt <- hansard_members(verbose = TRUE) which does work (returns a df length 12 with 4434 rows). In the main package funs I also notice that members() default is returning as expected (length 12, nrow 4434). So the problem seems to be limited to members_search(). If you can reproduce the problem on members_search() this may help with tracking down the problem. 

Session info below if that is useful

Many thanks again for the package! 

All the best, 

Paul 

R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] hansard_0.5.5

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13     lubridate_1.7.1  tidyr_0.7.2      dplyr_0.7.4     
 [5] assertthat_0.2.0 R6_2.2.2         jsonlite_1.5     magrittr_1.5    
 [9] httr_1.3.1       stringi_1.1.6    rlang_0.1.6      curl_3.0        
[13] bindrcpp_0.2     tools_3.4.3      stringr_1.2.0    glue_1.2.0      
[17] purrr_0.2.4      yaml_2.1.16      compiler_3.4.3   pkgconfig_2.0.1 
[21] bindr_0.1        knitr_1.18       tibble_1.3.4

**Comment by evanodell** [comment]
Hi Paul,

Thanks for catching that, is now fixed in the latest development version. The problem was that if `members_search` was left empty it attempted to use a now defunct method of retrieving all members, instead of just calling `members` without any parameters, which it now does.
